#!/bin/sh

# This script is run during startup as root, asynchronously

# Update customize_environment (works as * expands to just one user)
curl -fsSL https://raw.githubusercontent.com/nostra/dotfiles/master/_customize_environment > /home/*/.customize_environment

# Remove default help script file
rm -f /etc/profile.d/init_help.sh

# Customize welcome file
wget -P /etc/profile.d/ https://raw.githubusercontent.com/nostra/dotfiles/master/init_welcome.sh
chmod +x /etc/profile.d/init_welcome.sh

# Install zsh
sudo apt-get update
sudo apt install -y zsh

# Install VSCode server
# From: https://medium.com/google-cloud/how-to-run-visual-studio-code-in-google-cloud-shell-354d125d5748
# curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run | sed 's|~/.cache|/tmp/cache|g'
curl -fsSL https://code-server.dev/install.sh | sed 's|~/.cache|/tmp/cache|g' | sh -s --
# Start server when desired with:  code-server --no-auth --port 8080
